interface observe {
  enum metric-format {
    statsd,
  }

  /// Emit a metric.
  ///
  /// A metric has a `format` describing the format of the `name` parameter.
  metric: func(format: metric-format, name: string);

  /// Enter a named span.
  ///
  /// Communicate to the o11y host that the guest is moving into a new span.
  span-enter: func(name: string);

  /// Add tags to the current span.
  ///
  /// Add a comma-delimited list of tags to the active span.
  span-tags: func(tags: string);

  /// Exit the current span.
  ///
  /// Communicate to the o11y host that the span is complete.
  span-exit: func();
}
